import type { Metadata } from "next";
import { site } from "@/site.config";
import { Icon, Section, SectionHead } from "@/components/ui";
import { ClosingCta, PageHero } from "@/components/blocks";

export const metadata: Metadata = {
  title: "Our Promise: No Pressure, No Expiring Discounts",
  description:
    "How Michigan Shower quotes and sells: a written quote good for 30 days, no same-day signing, no discount that disappears overnight, and the same price whether you decide today or next month.",
  alternates: { canonical: "/promise" },
};

const promises = [
  {
    icon: "doc" as const,
    title: "The quote is in writing, and it is good for 30 days",
    body: "You get an itemized number on paper. It does not change because you waited a week, and it does not expire at midnight. Take it to your spouse, your kids, or another contractor. That is what a real quote is for.",
  },
  {
    icon: "clock" as const,
    title: "We will not ask you to sign on the first visit",
    body: "There is no manager to call for a special authorization. No price that drops the moment you hesitate. If the number falls when you say no, it was never the number. We would rather come back in three weeks than push you into something today.",
  },
  {
    icon: "check" as const,
    title: "One price, honestly arrived at",
    body: "We do not inflate a list price so a discount can bring it back down. Our price is our price. If you see 70% off somewhere else, ask what the 100% was.",
  },
  {
    icon: "accessible" as const,
    title: "Bring whoever you want to the consultation",
    body: "An adult child, a friend, a contractor you trust. We will happily wait while you call someone. A lot of our work is for people making a hard decision about mobility, and nobody should make that decision alone or in a hurry.",
  },
  {
    icon: "shield" as const,
    title: "If we are not the right fit, we will say so",
    body: "Sometimes the honest answer is a smaller job than you asked for, or a different trade entirely, or waiting a season. We would rather tell you that than sell you something you did not need.",
  },
  {
    icon: "sparkle" as const,
    title: "We label our photography honestly",
    body: "The finish images on this site are manufacturer product photography of the exact systems we install, and we say so rather than passing them off as our own jobs. Nothing here is stock imagery of a bathroom we had no part in, and nothing here was generated by a computer.",
  },
];

export default function PromisePage() {
  return (
    <>
      <PageHero
        eyebrow="Our promise"
        title="No pressure. No expiring discount. No theater."
        intro="This industry earned its reputation honestly, and the sales appointment is where most of it was earned. So here is exactly how we sell, in writing, for you to hold us to."
      />

      <Section tone="white">
        <div className="grid gap-6 md:grid-cols-2">
          {promises.map((p) => (
            <div
              key={p.title}
              className="rounded-2xl bg-cream-100 p-7 ring-1 ring-ink/8"
            >
              <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-white text-brand-600">
                <Icon name={p.icon} className="h-6 w-6" />
              </span>
              <h2 className="h-display mt-5 text-xl text-ink">{p.title}</h2>
              <p className="mt-3 text-[0.95rem] leading-relaxed text-ink-soft">
                {p.body}
              </p>
            </div>
          ))}
        </div>
      </Section>

      <Section tone="deep">
        <div className="mx-auto max-w-3xl text-center">
          <SectionHead
            eyebrow="Why we bother writing this down"
            title="Because the alternative is everywhere."
            align="center"
            invert
          />
          <div className="prose-ms mt-8 text-left text-[1.05rem] sm:text-center">
            <p className="text-brand-100">
              Search for a bathroom remodel and you will find countdown timers,
              percentages off labor that never end, and quotes that arrive only
              after a salesperson is sitting in your living room. Consumer
              guides now advise homeowners to have a family member present
              during in-home bath consultations. That is the state of this
              industry.
            </p>
            <p className="text-brand-100">
              We are a Michigan company. The person who quotes your bathroom
              works here, the crew that builds it works here, and we will still
              be the ones answering the phone in five years. That is the whole
              pitch, and it is the reason none of the above is necessary.
            </p>
          </div>
        </div>
      </Section>

      <ClosingCta
        title="Ready when you are. Not before."
        body={`Send a few details or call ${site.phone}. We will look at the bathroom, give you a written number, and leave you alone to think about it.`}
      />
    </>
  );
}
