import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { products } from "@/lib/products";
import { site } from "@/site.config";
import { Button, Icon, Section, SectionHead } from "@/components/ui";
import { ClosingCta, PageHero } from "@/components/blocks";

export const metadata: Metadata = {
  title: "Products: Samuel Mueller Wall Systems and Bases",
  description:
    "Michigan Shower installs Samuel Mueller Pioneer, Pioneer Plus and Monterey wall systems and TrimSlate shower bases. Grout-free surfaces, seven Monterey colorways, and zero-threshold bases for roll-in access.",
  alternates: { canonical: "/products" },
};

const comparison = [
  {
    label: "Material",
    values: [
      "Acrylic panel",
      "Acrylic, trimmable sides",
      "Solid surface",
      "Solid surface base",
    ],
  },
  {
    label: "Grout",
    values: ["None", "None", "None", "Not applicable"],
  },
  {
    label: "Colorways",
    values: ["6 patterns", "8", "7 colors, 2 finishes each", "White, black, greys"],
  },
  {
    label: "Handles out-of-square rooms",
    values: ["Standard fit", "Trimmable side walls", "Standard fit", "Adjustable threshold"],
  },
  {
    label: "Typical use",
    values: [
      "Tub-to-shower conversion",
      "Older homes, stone looks",
      "Primary bath, whole remodel",
      "Every accessible build",
    ],
  },
];

export default function ProductsPage() {
  return (
    <>
      <PageHero
        eyebrow="Products"
        title="What we actually put in your bathroom."
        intro="We install Samuel Mueller wall systems and bases. Three wall lines and one base line, all grout-free, all with matching components rather than parts from three suppliers. Here is the honest difference between them."
      />

      {/* Partner band */}
      <section className="border-b border-ink/8 bg-brand-950 py-10">
        <div className="mx-auto flex max-w-6xl flex-col items-center gap-6 px-5 text-center sm:px-8 md:flex-row md:text-left">
          <Image
            src="/brand/samuel-mueller-white.png"
            alt="Samuel Mueller"
            width={520}
            height={364}
            sizes="180px"
            className="h-14 w-auto shrink-0"
          />
          <p className="text-[0.95rem] leading-relaxed text-brand-100">
            Every product image on these pages is manufacturer photography
            supplied by Samuel Mueller, and we label it as such. Photographs of
            finished bathrooms in{" "}
            <Link
              href="/gallery"
              className="font-semibold text-white underline underline-offset-4"
            >
              our gallery
            </Link>{" "}
            are jobs we built. We do not mix the two, and nothing on this site
            is generated by a computer.
          </p>
        </div>
      </section>

      {/* Line cards */}
      <Section tone="white">
        <div className="grid gap-6 lg:grid-cols-2">
          {products.map((p) => (
            <article
              key={p.slug}
              className="group flex flex-col overflow-hidden rounded-2xl bg-white ring-1 ring-ink/8"
            >
              <Link href={`/products/${p.slug}`} className="block">
                <div className="aspect-4/3 overflow-hidden bg-cream-100">
                  <Image
                    src={p.hero.src}
                    alt={p.hero.alt}
                    width={p.hero.w}
                    height={p.hero.h}
                    sizes="(min-width: 1024px) 50vw, 100vw"
                    className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"
                  />
                </div>
              </Link>
              <div className="flex flex-1 flex-col p-7">
                <p className="eyebrow">{p.eyebrow}</p>
                <h2 className="h-display mt-2 text-2xl text-ink">
                  <Link href={`/products/${p.slug}`}>{p.name}</Link>
                </h2>
                <p className="mt-1 text-[0.95rem] font-medium text-brand-700">
                  {p.tagline}
                </p>
                <p className="mt-3 flex-1 text-[0.95rem] leading-relaxed text-ink-soft">
                  {p.summary}
                </p>
                <Link
                  href={`/products/${p.slug}`}
                  className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand-700 hover:text-brand-800"
                >
                  See {p.name} colorways
                  <Icon name="arrowRight" className="h-4 w-4" />
                </Link>
              </div>
            </article>
          ))}
        </div>
      </Section>

      {/* Comparison */}
      <Section tone="cream">
        <SectionHead
          eyebrow="Side by side"
          title="Which line is right for your bathroom?"
          intro="Most of our tub-to-shower conversions are Pioneer or Pioneer Plus. Most whole-bath remodels are Monterey. Every accessible build uses a TrimSlate base regardless of which walls go on it."
        />
        <div className="mt-10 overflow-x-auto">
          <table className="w-full min-w-[720px] border-collapse text-left text-[0.9rem]">
            <thead>
              <tr>
                <th className="w-44 pb-4 pr-4 align-bottom text-xs font-bold uppercase tracking-[0.12em] text-ink-soft">
                  &nbsp;
                </th>
                {products.map((p) => (
                  <th key={p.slug} className="px-4 pb-4 align-bottom">
                    <Link
                      href={`/products/${p.slug}`}
                      className="h-display text-lg text-ink hover:text-brand-700"
                    >
                      {p.name}
                    </Link>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {comparison.map((row) => (
                <tr key={row.label} className="border-t border-ink/10">
                  <th className="py-4 pr-4 align-top text-xs font-bold uppercase tracking-[0.12em] text-ink-soft">
                    {row.label}
                  </th>
                  {row.values.map((v, i) => (
                    <td
                      key={i}
                      className="px-4 py-4 align-top leading-relaxed text-ink"
                    >
                      {v}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-10 rounded-2xl bg-white p-7 ring-1 ring-ink/8">
          <h3 className="h-display flex items-center gap-3 text-xl text-ink">
            <Icon name="accessible" className="h-6 w-6 text-brand-600" />
            Building for accessibility?
          </h3>
          <p className="mt-3 max-w-3xl text-[0.95rem] leading-relaxed text-ink-soft">
            Start with the base, not the walls. A zero-threshold TrimSlate base
            is what makes a roll-in shower possible, and it is the configuration
            the VA names as an eligible HISA improvement. Any of the three wall
            lines can go on top of it.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Button href="/products/trimslate-bases" variant="secondary">
              TrimSlate bases
              <Icon name="arrowRight" className="h-4 w-4" />
            </Button>
            <Button href="/hisa-grants" variant="secondary">
              How HISA grants work
            </Button>
          </div>
        </div>
      </Section>

      <ClosingCta
        title="Hold the samples yourself."
        body={`Photographs only get you so far with a surface. We bring the physical samples to your bathroom so you can see them in your own light. Call ${site.phone} or send us a few details.`}
      />
    </>
  );
}
